### ISSUE TITLE
TypeError while uploading results locally

### ISSUE THREAD

**Issue by raghunath24** [aaronweaver/defectdojo_api#13]
Trying to upload the arachni scan results into local setup of defectdojo and facing the below type error. Any idea how to resolve? 

pip status: 
defectdojo_api 1.1.4

Command:

`python  defectdojo_api/examples/dojo_ci_cd.py --product 1 --file "defectdojo_api/examples/sample-scan-files/arachni/arachni.afr.json" --scanner=“Arachni Scan" --host="http://192.168.9.9/" --api_key="xxx" --user=“admin"`

Output:
```
Traceback (most recent call last):
  File "dojo_ci_cd.py", line 241, in <module>
    class Main:
  File "dojo_ci_cd.py", line 290, in Main
    summary(dd, engagement_id, test_ids, max_critical, max_high, max_medium)
  File "dojo_ci_cd.py", line 166, in summary
    print "Total Number of Vulnerabilities: " + str(findings.data["meta"]["total_count"])
TypeError: string indices must be integers
```

**Comment by wurstbrot** [comment]
@ # @
Duplicate of 11#

Please try `pip install -I defectdojo_api==1.1.3`
